services:
  - type: web
    name: plexisystem-backend
    runtime: node
    buildCommand: cd plexisystem-backend && npm install
    startCommand: cd plexisystem-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /var/data/plexisystem.db
      - key: PORT
        value: 3001
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
