services:
  - type: web
    name: plexisystem-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://oferty.plexisystem.pl
      - key: DATABASE_PATH
        value: /var/data/plexisystem.db
      - key: SMTP_HOST
        value: s44.cyber-folks.pl
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        value: oferty@plexisystem.pl
      - key: SMTP_PASS
        value: 36ZVvm^D-E-Zi_-D
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1